# ./docker-compose.yml (项目根目录)
services:
    # PHP 应用服务
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: dalaran_app # 容器名加上项目前缀避免冲突
        restart: unless-stopped
        working_dir: /var/www/html # 容器内工作目录
        volumes:
            # 将本地代码映射到容器内的 /var/www/html
            # 这会覆盖 Dockerfile 中的 COPY 指令（如果在构建时使用了）
            # 部署时服务器上的路径是 /var/www/dalaran
            - ./:/var/www/html
            # (可选) 挂载自定义 php.ini
            # - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - default # 项目内部网络
        depends_on: # 可选，确保依赖服务先启动 (但不保证完全就绪)
            - db
            - cache

    # 项目内部 Nginx 服务 (不直接对外)
    web:
        image: nginx:alpine
        container_name: dalaran_web # 容器名加上项目前缀
        restart: unless-stopped
        volumes:
            - ./:/var/www/html # 共享代码
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf # 挂载 Nginx 配置
        networks:
            - default
            - sharednet # ★ 连接到外部共享网络，供全局反向代理访问
        depends_on:
            - app

    # 数据库服务 (MySQL)
    db:
        image: mysql:8.0
        container_name: dalaran_db # 容器名加上项目前缀
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-dalaran}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret} # 使用环境变量，本地用 .env, 服务器用系统变量
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_USER: ${DB_USERNAME:-user}
        volumes:
            # 使用具名 volume 持久化数据，名称加上项目前缀
            - dalaran_db_data:/var/lib/mysql
        networks:
            - default # 通常只在内部网络

    # 缓存服务 (Redis)
    cache:
        image: redis:alpine
        container_name: dalaran_cache # 容器名加上项目前缀
        restart: unless-stopped
        networks:
            - default # 通常只在内部网络

# 网络定义
networks:
    default: # 项目内部网络
        driver: bridge
    sharednet: # 引用外部共享网络
        external: true # 必须设置为 true
        name: shared-proxy-network # ★ 必须与服务器上创建的网络名称一致

# 数据卷定义
volumes:
    dalaran_db_data: # 卷名加上项目前缀
        driver: local
